### ISSUE TITLE
BUG: "The billing details for some of your membership levels..." warning still displayed while plugin is active.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-stripe-billing-limits#5]
The "The billing details for some of your membership levels is not supported by Stripe. Please edit your levels." and "Stripe integration currently does not support billing limits. You can still set an expiration date below. " warnings, etc. are still displayed while the plugin is activated. 
This may confuse users who aren't aware of the plugin.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/stripe-gateway-installment-settings/

**Comment by kimcoleman** [comment]
We have resolved this in this PR to the core Paid Memberships Pro plugin here: https://github.com/strangerstudios/paid-memberships-pro/pull/1147
